# Generated by Django 5.0 on 2024-02-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
