# Generated by Django 3.2.13 on 2024-05-05 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_parent'),
        ('opinion', '0002_alter_opinion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.tag'),
        ),
    ]
