# Generated by Django 5.0 on 2024-02-18 09:47

import tags.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(max_length=50, validators=[tags.models.validate_tag_name]),
        ),
    ]
